version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.0
    networks:
      - shoaib-prac
    tmpfs: "/datalog"
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - zookeeper
    networks:
      - shoaib-prac
    ports:
      - "29092:29092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  shoaib-prac:
